#!/bin/sh
pkill herbe
case $1 in 
	"-")
		amixer set 'Master' 10%-
		herbe "$(amixer get Master | grep -E -o '[0-9]{1,3}%')"
		;;
	"+")
		amixer set 'Master' 10%+
		herbe "$(amixer get Master | grep -E -o '[0-9]{1,3}%')"
		;;
	"=")
		amixer set Master toggle | grep off && herbe "volume muted" || herbe "volume unmuted"
		;;
esac
